export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FALIURE: 'LOGIN_FALIURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILED: 'LOGOUT_FAILED',
    SIGN_UP_REQUEST: 'SIGNUP_REQUEST',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    GET_ALL_REQUEST :"GET_ALL_REQUEST",
    GET_ALL_SUCCESS : "GET_ALL_SUCCESS",
    GET_ALL_FAILURE : "GET_ALL_FAILURE",
    DELETE_REQUEST: "DELETE_REQUEST",
    DELETE_SUCCESS: "DELETE_SUCCESS",
    DELETE_FAILURE: "DELETE_FAILURE",
}

export const cartConstant ={
    GET_CART_REQUEST : 'GET_CART_REQUEST',
    GET_CART_SUCCESS : 'GET_CART_SUCCESS',
    GET_CART_FAILURE : 'GET_CART_FAILURE',
    DELETE_CART_REQUEST : 'DELETE_CART_REQUEST',
    DELETE_CART_SUCCESS : 'DELETE_CART_SUCCESS',
    DELETE_CART_FAILED  :  'DELETE_CART_FAILED'
}

export const orderConstant ={
    ACCEPT_ORDER_REQUEST : 'ACCEPT_ORDER_REQUEST',
    ACCEPT_ORDER_SUCCESS : 'ACCEPT_ORDER_SUCCESS',
    ACCEPT_ORDER_FAILURE : 'ACCEPT_ORDER_FAILURE',
    GET_ORDERS_REQUEST : 'GET_ORDERS_REQUEST',
    GET_ORDERS_SUCCESS : 'GET_ORDERS_SUCCESS',
    GET_ORDERS_FAILURE : 'GET_ORDERS_FAILURE',

}

export const sellerConstant ={
    GET_SELLER_REQUEST : 'GET_SELLER_REQUEST',
    GET_SELLER_SUCCESS : 'GET_SELLER_SUCCESS',
    GET_SELLER_FAILURE : 'GET_SELLER_FAILURE',
    SELLER_COM_REQUEST : 'SELLER_COM_REQUEST',
    SELLER_COM_SUCESS  : 'SELLER_COM_SUCESS',
    SELLER_COM_FAILURE : 'SELLER_COM_FAILURE'

}
export const commissionConstant ={
    GET_COMMISSION_REQUEST : 'GET_COMMISSION_REQUEST',
    GET_COMMISSION_SUCCESS : 'GET_COMMISSION_SUCCESS',
    GET_COMMISSION_FAILURE : 'GET_COMMISSION_FAILURE',

}